import type { Metadata } from "next";
import { Pirata_One, Ubuntu } from "next/font/google";
import "./globals.css";

// gonna use ubuntu and pirata one cause they look sick
const ubuntu = Ubuntu({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-ubuntu", 
});

const pirataOne = Pirata_One({
  weight: "400",
  subsets: ["latin"], 
  variable: "--font-pirata-one", 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-y-hidden">
      <body
        className={`${ubuntu.variable} ${pirataOne.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
